const USER_DETAILS_LOADING="userloading"
const USER_DETAILS_SUCCESS="usersuccess"
const USER_DETAILS_ERROR="usererror"
const USER_DELETE_LOADING="userdeleteloading"
const USER_DELETE_SUCCESS="userdeletesuccess"
const USER_DELETE_ERROR="userdeleteerror"

export {USER_DETAILS_LOADING,USER_DETAILS_SUCCESS,USER_DETAILS_ERROR , USER_DELETE_LOADING , USER_DELETE_SUCCESS ,USER_DELETE_ERROR}